name: Release (GitHub/PyPI)

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release:
    permissions:
      contents: write
    uses: Billingegroup/release-scripts/.github/workflows/_build-wheel-release-upload.yml@v0
    with:
      project: diffpy.nmf_mapping
    secrets:
      PYPI_TOKEN: $